### PR TITLE
Replace boilerplate in README

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Review by aendra-rininsland — APPROVED** [review]
Lol weird — cool though! Thanks! 👏

**Comment by amilajack** [comment]
What's weird about the PR? Anything I should change?

**Comment by aendra-rininsland** [comment]
Nope! Was just unexpected, that's all! 👍

**Comment by amilajack** [comment]
The reason why I made the change was because I added the app to electron-react-boilerplate's [new "showcases" page](https://electron-react-boilerplate.js.org/docs/app-showcase#vocab-https-githubcom-ft-interactive-vocab-by-financial-times-https-wwwftcom). I updated the readme to give the project a better introduction to people who were trying to understand the project

**Comment by aendra-rininsland** [comment]
@amilajack Ahh! Didn't realise! Very cool, thanks again! 😄

**Pull request merged**
